[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta:__legacy__"

[project]
name = "ass-computational-proj-structure"
version = "1.0.0"
license = "MIT"
description = ""
requires-python = ">=3.11"
dependencies = [
    "loguru",
]

[tool.setuptools.packages.find]
where = ["src"]
